# Generated by Django 3.2.9 on 2021-11-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Колонки')),
            ],
            options={
                'verbose_name': 'Карточки',
                'verbose_name_plural': 'Карточка',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Заголовок')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.columns', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задача',
            },
        ),
    ]
