# Generated by Django 3.2.9 on 2021-11-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columns',
            options={'verbose_name': 'Колонка', 'verbose_name_plural': 'Колонки'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.columns', verbose_name='Задача'),
        ),
    ]
